Trista's and Sofia's chatbot, w2
Technigo/project-chatbot pull request #255
Opened 2024-02-16 15:12 UTC by sofia32057

## Netlify link
[tristas-and-sofias-chatbot.netlify.app](https://tristas-and-sofias-chatbot.netlify.app/)

## Collaborators
[trista1987]

2024-02-21 12:59 UTC, HIPPIEKICK requested changes
Good job with your chatbot Trista & Sofia! I like that you made the project your own by using the createElement method and using some fun input types (range slider 🥳). Overall your code is organized and clean, but I would like to ask you to clean it up just a tiny bit by:
- being consistent with whether you're using semi-colons or not
- being consistent with whether you're using single or double quotes

and apart from that - fix the little bug that allows the user to order 0 pizzas, and then you're good to go.

Feel free to reach out on Stack Overflow if you have any doubts about how to approach it!

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +let confirmPrice = ""
Maybe this could be of type boolean? 👀

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +const inputWrapper = document.getElementById("input-wrapper") // Select the input wrapper
Make sure to be consistent with whether you're using single or double quotes

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +  setTimeout(() => chooseFood(), 1000) // Go to next step, chooseFood
If you don't pass any params, you could just write like this:
`setTimeout(chooseFood, 1000)`

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +  displayFood();
Are you using semi-colons or not? 😉 Make up your minds

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +}
I love that you chose a range slider for this question! You need to validate the input here though, it doesn't make sense to be able to order 0 pizzas.

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +    orderValue = partySize *onePastaPrice
Tiny thing, but it's the tiny things that adds up to make the code look clean - there should be a space between the * and the variable 🔍

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +const userConfirm = () => {
Could this function be called something like confirmPurchase or confirmOrder?

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +}
Nice!

2024-02-21 12:59 UTC, HIPPIEKICK commented on code/script.js
> +
It's enough to end with one empty line 😊

2024-02-23 13:41 UTC, AntonellaMorittu approved these changes

2024-02-26 20:50 UTC, trista1987 commented on code/script.js
> +let confirmPrice = ""
if change it to be boolean. Shoud I write `let onePizzaPrice = true` ? I'm a little confused. Could you please explain more? 😃

2024-09-02 09:14 UTC, closed without merging