Paula and Annikas chatbot
Technigo/project-chatbot pull request #264
Opened 2024-02-18 13:45 UTC by annsig

## Netlify link
https://soft-granita-58a603.netlify.app/

## Collaborators
[paulajungaker]

2024-02-18 13:46 UTC, annsig commented
The Netlify link didn't seem to work. It works locally, though. Would love to get help to get Netlify working!

2024-02-23 09:49 UTC, AntonellaMorittu commented
Hello 👋 I am a bit concerned that you're still experiencing issues with deploying the apps. Why there is no questions on SO or during Q&A about this issue? Please check the guide [here](https://www.notion.so/technigo/Netlify-A-guide-to-publishing-your-site-a4c46a8223bd4fdc8372c5018f997f54) or open a question on Stack Overflow where you explain step by step what is your procedure so to get support. 
My guess why it's not working: under Deploy settings - you should write `code` as the Publish Directory, are you doing it now? Please submit a working link to get the project approved 👍

2024-02-23 10:10 UTC, annsig commented
Hi Antonella, sorry for not speaking up about it before, I tried changing the Public Directory to code, it fixed the issue, our project is viewable now, Thank you Antonella!
________________________________
From: Antonella Morittu ***@***.***>
Sent: Friday, February 23, 2024 9:49 AM
To: Technigo/project-chatbot ***@***.***>
Cc: Annika Sigfridsson ***@***.***>; Author ***@***.***>
Subject: Re: [Technigo/project-chatbot] Paula and Annikas chatbot (PR #264)


Hello 👋 I am a bit concerned that you're still experiencing issues with deploying the apps. Why there is no questions on SO or during Q&A about this issue? Please check the guide here<https://www.notion.so/technigo/Netlify-A-guide-to-publishing-your-site-a4c46a8223bd4fdc8372c5018f997f54> or open a question on Stack Overflow where you explain step by step what is your procedure so to get support.
My guess why it's not working: under Deploy settings - you should write code as the Publish Directory, are you doing it now? Please submit a working link to get the project approved 👍

—
Reply to this email directly, view it on GitHub<https://github.com/Technigo/project-chatbot/pull/264#issuecomment-1961019874>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFMMNULAHD4CLDG2IIV5OR3YVBQ2RAVCNFSM6AAAAABDOFTZLCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRRGAYTSOBXGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-23 12:16 UTC, AntonellaMorittu requested changes
Hello ladies, good job submitting your work 🤖 Have you tested the app to check the behaviour? Step 4 and 5 are missing, you need to continue, after adding some questions with options (following the instructions), to get a response for the bot, and at some point say bye and give meaning to the interaction. If you need help reach out using our support tools. Almost there 💪

2024-02-23 15:32 UTC, annsig commented
Hi Antonella, thanks for the review, The site is updated now and includes a question with options, and a bye message in the end.

2024-02-26 07:16 UTC, AntonellaMorittu approved these changes

2024-09-02 09:14 UTC, closed without merging